### ISSUE TITLE
CI build failing for release/core_1.0rc/0.4

### ISSUE THREAD

**Issue by ThomasKroes** [ManiVaultStudio/t-SNE-Analysis#106]
The CI build for [release/core_1.0rc/0.4](https://github.com/ManiVaultStudio/t-SNE-Analysis/tree/release/core_1.0rc/0.4) is [failing](https://github.com/ManiVaultStudio/t-SNE-Analysis/actions/runs/8113061181/job/22175630791):

```
-- result length 0
CMake Error at cmake/InstallArtifactoryPackage.cmake:65 (message):
  No matching artifactory packages found.  Please check the query.
Call Stack (most recent call first):
  cmake/InstallArtifactoryPackage.cmake:119 (find_artifactory_package)
  cmake/InstallArtifactoryPackage.cmake:163 (get_artifactory_package)
  CMakeLists.txt:71 (install_artifactory_package)


-- Configuring incomplete, errors occurred!
SNEAnalyses/0.4@lkeb/stable: ERROR: Package 'fb77e92815a70b44df67dd1e39119092d04dc5b7' build failed
SNEAnalyses/0.4@lkeb/stable: 
SNEAnalyses/0.4@lkeb/stable: WARN: Build folder /home/runner/work/t-SNE-Analysis/t-SNE-Analysis/_conan/.conan/data/SNEAnalyses/0.4/lkeb/stable/build/fb77e92815a70b44df67dd1e39119092d04dc5b7
ERROR: SNEAnalyses/0.4@lkeb/stable: Error in build() method, line 141
	cmake = self._configure_cmake()
```
, despite the changes below:
```
matrix:
    include:
      - name: Windows-msvc2019
        os: windows-2019
        compiler: msvc-2019
        build-cversion: 16
        build-runtime: MD
        build-config: Release
      - name: Linux_gcc11
        os: ubuntu-22.04
        build-cc: gcc
        build-cxx: g++
        build-compiler: gcc
        build-cversion: 11
        build-config: Release
        build-os: Linux
        build-libcxx: libstdc++
      - name: Macos_xcode13.4
        os: macos-12
        build-compiler: apple-clang
        build-cversion: 13
        build-config: Release
        build-os: Macos
        build-xcode-version: 13.4
        build-libcxx: libc++
```
